on:
  - push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Z3
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: '4.8.10'
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.4'
      - name: Install Package and its Dependencies
        run: raco pkg install --auto --batch
      - name: Compile
        run: raco make main.rkt
