on:
  - push

env:
  Z3_URL: "https://github.com/Z3Prover/z3/releases/download/z3-4.8.14/z3-4.8.14-x64-glibc-2.31.zip"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Z3
        run: |
          mkdir bin                  &&
          wget $Z3_URL -nv -O bin/z3 &&
          chmod +x bin/z3
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.6.1
        with:
          architecture: 'x64'
          distribution: 'full'
          version: '8.4'
      - name: Install Package and its Dependencies
        run: raco pkg install --auto --batch
      - name: Compile
        run: raco make main.rkt
